### PR TITLE
fix: ensure a spark application can only be submitted once

### LINKED ISSUE #457: operator resubmits all spark applications after restart no matter what their status is
### Affected Stackable version

24.7

### Affected Apache Spark-on-Kubernetes version

3.4.2

### Current and expected behavior

when the spark-k8s operator restarts (e.g. in case of node restart or operator upgrade) every spark application is reconciled/resubmitted at once. this leads to hell and chaos because of both resource consumption and multiple jobs writing / reading one file which usually done ordered by airflow dags doing the spark submits

### Possible solution

not submitting an application which is in state succeeded / failed / stopped / killed. maybe even running apps should not be restarted because they are already running

### Additional context

_No response_

### Environment

_No response_

### Would you like to work on fixing this bug?

None

### PR DESCRIPTION
**Pull request by razvan**
# Description

Fixes #457

Kubernetes recycles Spark applications jobs after `ttlSecondsAfterFinished` (10min currently) but the application objects live forever (or until the user deletes them).
If a reconciliation is triggered on an app that has no child Job, the operator will submit the Job again.

The fix is to use the application's status field as guard for the reconciliation loop.

I tested it by:

1. running the smoke integration test with `--skip-delete`
2. After the test finished successfully I deleted the  Spark pi Job object
3. I deleted the operator pod (simulated a restart)
4. The Job was not submitted again and in the operator logs I see:

```
│ 2024-09-12T13:14:51.650689Z  INFO app_controller:reconciling object{object.ref=SparkApplication.v1alpha1.spark.stackable.tech/spark-pi-s3-1.kuttl-test-meet-martin object.reason=object updated}: stackable_spark │
│ _k8s_operator::spark_k8s_controller: Skip reconciling SparkApplication [spark-pi-s3-1] with non empty status  
```

:green_circle: CI: https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/spark-k8s-operator-it-custom/4/

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [x] Changes are OpenShift compatible
- [x] CRD changes approved
- [x] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [x] Helm chart can be installed and deployed operator works
- [x] Integration tests passed (for non trivial changes)
- [x] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [x] Code contains useful comments
- [x] Code contains useful logging statements
- [x] (Integration-)Test cases added
- [x] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [x] Changelog updated
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

### CODE REVIEW

File: rust/operator-binary/src/spark_k8s_controller.rs [hunk 1]
```diff
@@ -170,6 +175,16 @@ pub async fn reconcile(spark_application: Arc<SparkApplication>, ctx: Arc<Ctx>)
 
     let client = &ctx.client;
 
+    // Fix for #457
+    // Skip reconcyling the SparkApplication if it has a non empty status.
+    if spark_application.status.is_some() {
```
Comment (sbernauer) [inline rust/operator-binary/src/spark_k8s_controller.rs:180]: I think it makes sense to move this to a named function on `SparkApplication` with some docs: 
```rust
impl SparkApplication {
    /// Returns if this [`SparkApplication`] has already created a Kubernetes Job doing the actual `spark-submit`.
    ///
    /// This is needed because Kubernetes will remove the succeeded Job after some time. When the spark-k8s-operator is
    /// restarted it would re-create the Job, resulting in the Spark job running multiple times. This function assumes
    /// that the [`SparkApplication`]'s status will always be set when the Kubernetes Job is created. It therefore
    /// checks if the status is set to determine if the Job was already created in the past.
    ///
    /// See the bug report [#457](https://github.com/stackabletech/spark-k8s-operator/issues/457) for details.
    pub fn k8s_job_has_been_created(&self) -> bool {
        self.status
            .as_ref()
            .map(|s| !s.phase.is_empty())
            .unwrap_or_default()
    }
}
```

I did change the actual check to check the status is not empty, but I guess it's also ok to keep the current `status.is_some()` check

File: rust/operator-binary/src/spark_k8s_controller.rs [hunk 2]
```diff
@@ -170,6 +175,16 @@ pub async fn reconcile(spark_application: Arc<SparkApplication>, ctx: Arc<Ctx>)
 
     let client = &ctx.client;
 
+    // Fix for #457
+    // Skip reconcyling the SparkApplication if it has a non empty status.
```
Comment (sbernauer) [inline rust/operator-binary/src/spark_k8s_controller.rs:179]: As the docs are now on the `k8s_job_has_been_created` function
```suggestion
```

File: rust/operator-binary/src/spark_k8s_controller.rs [hunk 3]
```diff
@@ -170,6 +175,16 @@ pub async fn reconcile(spark_application: Arc<SparkApplication>, ctx: Arc<Ctx>)
...
+    if spark_application.status.is_some() {
+        tracing::info!(
+            "Skip reconciling SparkApplication [{}] with non empty status",
+            spark_application.name_any()
+        );
```
Comment (sbernauer) [inline rust/operator-binary/src/spark_k8s_controller.rs:184]: I *think* it's best practice to capture the variables using dedicated variables instead of including them in the text, but I would be interested in your opinion @NickLarsenNZ 
```suggestion
        tracing::info!(
            spark_application = spark_application.name_any(),
            "Skipped reconciling SparkApplication with non empty status"
        );
```

**Review by sbernauer — CHANGES_REQUESTED** [review]
Functionality LGTM, only some style questions

File: rust/operator-binary/src/spark_k8s_controller.rs (hunk 1 above)
Comment (razvan) [reply rust/operator-binary/src/spark_k8s_controller.rs]: Done

File: rust/operator-binary/src/spark_k8s_controller.rs [hunk 4]
```diff
@@ -155,6 +155,11 @@ pub enum Error {
     CreateVolumes {
         source: stackable_spark_k8s_crd::Error,
     },
+    #[snafu(display("Failed to update status for application [{name}]"))]
```
Comment (sbernauer) [inline rust/operator-binary/src/spark_k8s_controller.rs:158]: nit(optional): According to our style guide we space those apart when the have macro attributes or documentation on top
```suggestion

    #[snafu(display("Failed to update status for application [{name}]"))]
```

**Review by sbernauer — APPROVED** [review]
Thanks! Can you please run a Jenkins custom test before merge?

File: rust/operator-binary/src/spark_k8s_controller.rs [hunk 5]
```diff
@@ -155,6 +155,12 @@ pub enum Error {
     CreateVolumes {
         source: stackable_spark_k8s_crd::Error,
     },
+
+    #[snafu(display("Failed to update status for application [{name}]"))]
```
Comment (NickLarsenNZ) [inline rust/operator-binary/src/spark_k8s_controller.rs:159]: Since `name` is a String, I would then use the Debug impl which adds quotes.

```suggestion
    #[snafu(display("Failed to update status for application {name:?}"))]
```

**Review by sbernauer — APPROVED** [review]
Thanks!
